# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ POC ]
  pull_request:
    branches: [ POC ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Dummy run wrapper, so next will be updated xD
      run: gradle wrapper --gradle-version=4.6 --distribution-type=all --gradle-distribution-url=https\://services.gradle.org/distributions/gradle-4.6-all.zip
      continue-on-error: true
    - name: Set execute rights to gradlew
      run: chmod +x ./gradlew
    - name: Build with updated wrapper
      run: ./gradlew wrapper
