# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ POC ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        java-package: jdk
    - name: Set execute rights to gradlew
      run: chmod +x ./gradlew
    - name: Use wrapper
      run: ./gradlew wrapper
    - name: Build
      run: ./gradlew build
    - name: Publish desktop
      run: ./gradlew desktop:dist
    - name: Pack with packr.jar
      run: java -jar packr.jar packr-config.json
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ooc_win64
        path: ./bin/win64